import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const modules = ['src/protocol.js', 'src/transport.js', 'src/worker.js'];
const parts = [];
for (const name of modules) {
  let source = await readFile(resolve(root, name), 'utf8');
  source = source.replace(/^import .* from '\.\/[^']+';\n/gm, '');
  if (name !== 'src/worker.js') source = source.replace(/^export (?=(?:async )?(?:function|class|const) )/gm, '');
  parts.push('// ---- ' + name + ' ----\n' + source.trimEnd());
}
const bundle = '// Generated by npm run build. Edit src/; commit this file for Cloudflare Pages.\n' + parts.join('\n\n') + '\n';
const output = resolve(root, '_worker.js');
if (process.argv.includes('--check')) {
  if (await readFile(output, 'utf8') !== bundle) {
    console.error('_worker.js is out of date. Run npm run build.');
    process.exitCode = 1;
  }
} else {
  await writeFile(output, bundle);
  console.log('Built _worker.js (' + Buffer.byteLength(bundle) + ' bytes)');
}
